version: '2.3'

x-user:
  &default-user
    # The default user under which the containers should run. Change this if you are on linux and run with another user than id `1000`
    user: '1000'

services:
  commons:
    image: uselagoon/commons:latest
    << : *default-user # uses the defined user from top

  mariadb-10.4:
    image: uselagoon/mariadb-10.4:latest
    labels:
      lando.type: mariadb
    ports:
      - "3306" # exposes the port 3306 with a random local port, find it with `docker-compose port mariadb 3306`
    << : *default-user # uses the defined user from top

  mariadb-10.5:
    image: uselagoon/mariadb-10.5:latest
    labels:
      lando.type: mariadb
    ports:
      - "3306" # exposes the port 3306 with a random local port, find it with `docker-compose port mariadb 3306`
    << : *default-user # uses the defined user from top

  mariadb-10.6:
    image: uselagoon/mariadb-10.6:latest
    labels:
      lando.type: mariadb
    ports:
      - "3306" # exposes the port 3306 with a random local port, find it with `docker-compose port mariadb 3306`
    << : *default-user # uses the defined user from top

  mongo:
    image: uselagoon/mongo:latest
    ports:
      - "27017"
      - "28017"
    << : *default-user # uses the defined user from top

  node-14:
    image: uselagoon/node-14:latest
    labels:
      lando.type: node
    ports:
      - "3000" # exposes the port 6379 with a random local port, find it with `docker-compose port redis 6379`
    << : *default-user # uses the defined user from top

  node-16:
    image: uselagoon/node-14:latest
    labels:
      lando.type: node
    ports:
      - "3000" # exposes the port 6379 with a random local port, find it with `docker-compose port redis 6379`
    << : *default-user # uses the defined user from top

  node-18:
    image: uselagoon/node-18:latest
    labels:
      lando.type: node
    ports:
      - "3000" # exposes the port 6379 with a random local port, find it with `docker-compose port redis 6379`
    << : *default-user # uses the defined user from top
    
  postgres-11:
    image: uselagoon/postgres-11:latest
    labels:
      lando.type: postgres
    ports:
      - "5432" # exposes the port 3306 with a random local port, find it with `docker-compose port mariadb 3306`
    << : *default-user # uses the defined user from top

  postgres-12:
    image: uselagoon/postgres-12:latest
    labels:
      lando.type: postgres
    ports:
      - "5432" # exposes the port 3306 with a random local port, find it with `docker-compose port mariadb 3306`
    << : *default-user # uses the defined user from top


  postgres-13:
    image: uselagoon/postgres-13:latest
    labels:
      lando.type: postgres
    ports:
      - "5432" # exposes the port 3306 with a random local port, find it with `docker-compose port mariadb 3306`
    << : *default-user # uses the defined user from top


  postgres-14:
    image: uselagoon/postgres-14:latest
    labels:
      lando.type: postgres
    ports:
      - "5432" # exposes the port 3306 with a random local port, find it with `docker-compose port mariadb 3306`
    << : *default-user # uses the defined user from top

  python-3.7:
    image: uselagoon/python-3.7:latest
    << : *default-user # uses the defined user from top

  python-3.8:
    image: uselagoon/python-3.8:latest
    << : *default-user # uses the defined user from top

  python-3.9:
    image: uselagoon/python-3.9:latest
    << : *default-user # uses the defined user from top

  python-3.10:
    image: uselagoon/python-3.10:latest
    << : *default-user # uses the defined user from top
  rabbitmq:
    image: uselagoon/rabbitmq:latest
    << : *default-user # uses the defined user from top
    ports:
      - "5672" # exposes the port 3306 with a random local port, find it with `docker-compose port mariadb 3306`
      - "15672" # exposes the port 3306 with a random local port, find it with `docker-compose port mariadb 3306`

  redis-5:
    image: uselagoon/redis-5:latest
    labels:
      lando.type: redis
    ports:
      - "6379" # exposes the port 6379 with a random local port, find it with `docker-compose port redis 6379`
    << : *default-user # uses the defined user from top

  redis-6:
    image: uselagoon/redis-6:latest
    labels:
      lando.type: redis
    ports:
      - "6379" # exposes the port 6379 with a random local port, find it with `docker-compose port redis 6379`
    << : *default-user # uses the defined user from top

  solr-7:
    image: uselagoon/solr-7:latest
    labels:
      lando.type: solr
    ports:
      - "8983" # exposes the port 8983 with a random local port, find it with `docker-compose port solr 8983`

  solr-7.7:
    image: uselagoon/solr-7.7:latest
    labels:
      lando.type: solr
    ports:
      - "8983" # exposes the port 8983 with a random local port, find it with `docker-compose port solr 8983`

  solr-8:
    image: uselagoon/solr-8:latest
    labels:
      lando.type: solr
    ports:
      - "8983" # exposes the port 8983 with a random local port, find it with `docker-compose port solr 8983`
networks:
  amazeeio-network:
    external: true
