# Lagoon Version Update Helper
#
# Helper to update Version inside Dockerfiles
# Update versions below in `vars` and execute locally
#
# ansible-playbook helpers/update-versions.yml
- name: update versions
  hosts: 127.0.0.1
  connection: local
  vars:
    # Newrelic - https://docs.newrelic.com/docs/release-notes/agent-release-notes/php-release-notes/
    NEWRELIC_VERSION: '9.17.1.301'
    # Composer - https://getcomposer.org/download/
    COMPOSER_VERSION: '1.10.22'
    COMPOSER_HASH_SHA256: '6127ae192d3b56cd6758c7c72fe2ac6868ecc835dae1451a004aca10ab1e0700'
    # Drupal Console Launcher - https://github.com/hechoendrupal/drupal-console-launcher/releases
    DRUPAL_CONSOLE_LAUNCHER_VERSION: 1.9.7
    DRUPAL_CONSOLE_LAUNCHER_SHA: fe83050489c66a0578eb59d6744420be6fd4c5d1
    # Drush - https://github.com/drush-ops/drush/releases
    DRUSH_VERSION: 8.4.8
    # Drush Launcher Version - https://github.com/drush-ops/drush-launcher/releases
    DRUSH_LAUNCHER_VERSION: 0.9.1
  tasks:
  - name: Get a list of test*.conf in /home/user
    find:
        paths:
          - "{{ lookup('env', 'PWD') }}/images/php-fpm"
          - "{{ lookup('env', 'PWD') }}/images/php-cli"
          - "{{ lookup('env', 'PWD') }}/images/php-cli-drupal"
        patterns:
          - '*.Dockerfile'
    register: my_dockerfiles
  - name: update NEWRELIC_VERSION
    replace:
        path: "{{ item.path }}"
        regexp: 'ENV NEWRELIC_VERSION=.*'
        replace: 'ENV NEWRELIC_VERSION={{ NEWRELIC_VERSION }}'
    with_items: "{{ my_dockerfiles.files }}"
  - name: update COMPOSER_VERSION
    replace:
        path: "{{ item.path }}"
        regexp: 'ENV COMPOSER_VERSION=.*'
        replace: 'ENV COMPOSER_VERSION={{ COMPOSER_VERSION }} \\'
    with_items: "{{ my_dockerfiles.files }}"
  - name: update COMPOSER_HASH_SHA256
    replace:
        path: "{{ item.path }}"
        regexp: 'COMPOSER_HASH_SHA256=.*'
        replace: 'COMPOSER_HASH_SHA256={{ COMPOSER_HASH_SHA256 }}'
    with_items: "{{ my_dockerfiles.files }}"
  - name: update DRUPAL_CONSOLE_LAUNCHER_VERSION
    replace:
        path: "{{ item.path }}"
        regexp: 'ENV DRUPAL_CONSOLE_LAUNCHER_VERSION=.*'
        replace: 'ENV DRUPAL_CONSOLE_LAUNCHER_VERSION={{ DRUPAL_CONSOLE_LAUNCHER_VERSION }} \\'
    with_items: "{{ my_dockerfiles.files }}"
  - name: update DRUPAL_CONSOLE_LAUNCHER_SHA
    replace:
        path: "{{ item.path }}"
        regexp: 'DRUPAL_CONSOLE_LAUNCHER_SHA=.*'
        replace: 'DRUPAL_CONSOLE_LAUNCHER_SHA={{ DRUPAL_CONSOLE_LAUNCHER_SHA }} \\'
    with_items: "{{ my_dockerfiles.files }}"
  - name: update DRUSH_VERSION
    replace:
        path: "{{ item.path }}"
        regexp: 'DRUSH_VERSION=.*'
        replace: 'DRUSH_VERSION={{ DRUSH_VERSION }} \\'
    with_items: "{{ my_dockerfiles.files }}"
  - name: update DRUSH_LAUNCHER_VERSION
    replace:
        path: "{{ item.path }}"
        regexp: 'DRUSH_LAUNCHER_VERSION=.*'
        replace: 'DRUSH_LAUNCHER_VERSION={{ DRUSH_LAUNCHER_VERSION }} \\'
    with_items: "{{ my_dockerfiles.files }}"
