#!/bin/sh

if [[ -n "${REDIS_PASSWORD}" ]]; then
  export REQUIREPASS_CONF="# Enable basic/simple authentication
# Warning: since Redis is pretty fast an outside user can try up to
# 150k passwords per second against a good box. This means that you should
# use a very strong password otherwise it will be very easy to break.
requirepass ${REDIS_PASSWORD}"
fi

# Check if REDIS_FLAVOR or FLAVOR is set and has the value "persistent"
if [ "${REDIS_FLAVOR}" = "persistent" ] || [ "${FLAVOR}" = "persistent" ]; then
    FLAVOR="persistent"
else
    FLAVOR="ephemeral"
fi
echo "FLAVOR is set to: $FLAVOR"

ep /etc/redis/*

exec "$@"
