ARG IMAGE_REPO
FROM ${IMAGE_REPO:-lagoon}/mariadb

LABEL org.opencontainers.image.source=https://github.com/uselagoon/lagoon-images

ENV MARIADB_DATABASE=drupal \
    MARIADB_USER=drupal \
    MARIADB_PASSWORD=drupal
